version: '1.1'

services:
  node-backend:
    container_name: user_post_application
    image: user_posts_app:0.0.2
    build: 
       context: .
    ports:
      - "3000:3000"
    environment:
       - EXTERNAL_PORT=3000 
       - DB_NAME=user_db
       - DB_USER=nishit
       - DB_PASSWORD=123456
       - DB_HOST=node_db 
    depends_on:
       - node_db
  node_db:
       container_name : node_db
       image: "postgres:12"    
       ports:
       - "5432:5432"
       environment:
       - POSTGRES_USER=nishit
       - POSTGRES_PASSWORD=123456
       - POSTGRES_DB=user_db
       volumes:
       - nps_data:/var/lib/postgresql/nps_data

volumes:
    nps_data: {}