version: '1.1'

services:
  node-backend:
    container_name: user_post_application
    image: user_posts_app:0.0.2
    build: 
       context: .
    ports:
      - "3000:3000"
    environment:
       - EXTERNAL_PORT=3000     